package com.shrcn.tool.rtu.model;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.List;

import com.shrcn.found.common.util.ObjectUtil;
import com.shrcn.found.common.util.StringUtil;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TDcaSp generated by hbm2java
 */
public class BaseDcaPoint extends RowData {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int id;
	private String ref;
	private String fc;
	private String registerq;
	private String registert;
	private int subzone;
	private int sharednums;
	private int saddr;
	private String description;
	private int dcaindex;
	private String dattype;
	private String val;
	private int pointtype;
	private int qid;
	private int tid;
	private String md5;

	//103采集点属性
	private int groupID;
	private int entryID;
	private int fun;
	private int inf;
	
	//104采集点属性
	private int infoType;
	private int pointNum;
	private int reporttype;
	private String adiotype;
	
	// Modbus
	private float ratio;
	private int bit;
	private String bytes;
	private int length;
	private String dataType;
	private int objectID;
	private float threshold;
	// 仅用于Modbus 导出使用，对应模板.eq文件属性
	private int objId;

	private TDcald ld;
	private TDcaGroup group;
	private TDcaObject obj;
	private BaseDcaied ied;
	private boolean selected = false;
	private int used = 0;

	private List<TDcaPointRef> refs = new ArrayList<TDcaPointRef>();
	
	public BaseDcaPoint(int id, int dcaindex, int objId, int saddr,
			String desc, String fc, int objectID, int entryID, int pointNum) {
		this.id = id;
		this.dcaindex = dcaindex;
		this.objId = objId;
		this.saddr = saddr;
		this.description = desc;
		this.fc = fc;
		this.objectID = objectID;
		this.entryID = entryID;
		this.pointNum = pointNum;
	}

	public BaseDcaPoint(int id, int dcaindex, int objId, int saddr,
			String desc, String fc, int objectID, int entryID, int pointNum,
			float ratio, String bytes, int bit, String type, int length) {
		this(id, dcaindex, objId, saddr, desc, fc, objectID, entryID,
				pointNum);
		this.ratio = ratio;
		this.bytes = bytes;
		this.bit = bit;
		this.dataType = type;
		this.length = length;
	}
	public BaseDcaPoint(int id, int dcaindex, int objId, int saddr,
			String desc, String fc, int objectID, int entryID, int pointNum,
			float ratio, String bytes, int bit, String type, int length, float threshold) {
		this(id, dcaindex, objId, saddr, desc, fc, objectID, entryID,
				pointNum, ratio, bytes, bit, type, length);
		this.threshold = threshold;
	}

	public int getSaddr() {
		return saddr;
	}

	public void setSaddr(int saddr) {
		this.saddr = saddr;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getDcaindex() {
		return dcaindex;
	}

	public void setDcaindex(int dcaindex) {
		this.dcaindex = dcaindex;
	}

	public String getVal() {
		return val;
	}

	public void setVal(String val) {
		this.val = val;
	}

	public int getPointtype() {
		return pointtype;
	}

	public void setPointtype(int pointtype) {
		this.pointtype = pointtype;
	}

	public BaseDcaPoint() {
	}

	public BaseDcaPoint(int id) {
		this.id = id;
	}

	public BaseDcaPoint(int id, String ref, int subzone, int sharednums) {
		this.id = id;
		this.ref = ref;
		this.subzone = subzone;
		this.sharednums = sharednums;
	}

	public void assignBaseValues(BaseDcaPoint p) {
		try {
			Field[] fields = BaseDcaPoint.class.getDeclaredFields();
			for (Field f : fields) {
				if (!Modifier.isFinal(f.getModifiers()))
					f.set(p, f.get(this));
			}
		} catch (IllegalArgumentException e) {
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		}
		p.setDescription(StringUtil.nullToEmpty(description));
	}

	public BaseDcaPoint copy() {
		return (BaseDcaPoint) ObjectUtil.duplicate(this);
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getRef() {
		return this.ref;
	}

	public void setRef(String ref) {
		this.ref = ref;
	}

	public String getFc() {
		return fc;
	}

	public void setFc(String fc) {
		this.fc = fc;
	}

	public String getRegisterq() {
		return this.registerq;
	}

	public void setRegisterq(String registerq) {
		this.registerq = registerq;
	}

	public String getRegistert() {
		return this.registert;
	}

	public void setRegistert(String registert) {
		this.registert = registert;
	}

	public int getSubzone() {
		return this.subzone;
	}

	public void setSubzone(int subzone) {
		this.subzone = subzone;
	}

	public int getSharednums() {
		return this.sharednums;
	}

	public void setSharednums(int sharednums) {
		this.sharednums = sharednums;
	}

	public TDcald getLd() {
		return ld;
	}

	public void setLd(TDcald ld) {
		this.ld = ld;
	}

	public TDcaGroup getGroup() {
		return group;
	}

	public void setGroup(TDcaGroup group) {
		this.group = group;
	}
	
	public TDcaObject getObj() {
		return obj;
	}
	
	public void setObj(TDcaObject obj) {
		this.obj = obj;
	}

	public BaseDcaied getIed() {
		return ied;
	}

	public void setIed(BaseDcaied ied) {
		this.ied = ied;
	}

	public String getDattype() {
		return dattype;
	}

	public void setDattype(String dattype) {
		this.dattype = dattype;
	}

	public boolean isSelected() {
		return selected;
	}

	public void setSelected(boolean selected) {
		this.selected = selected;
	}

	public List<TDcaPointRef> getRefs() {
		return refs;
	}

	public void setRefs(List<TDcaPointRef> refs) {
		this.refs = refs;
	}

	public void addRef(TDcaPointRef ref) {
		getRefs().add(ref);
	}

	public String getLdref() {
		if (ld == null)
			return StringUtil.isEmpty(ref) ? "" : ref;
		return ld.getLdname() + "/" + ref;
	}

	public int getQid() {
		return qid;
	}

	public void setQid(int qid) {
		this.qid = qid;
	}

	public int getTid() {
		return tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	public boolean getHasq() {
		return qid > -1;
	}

	public boolean getHast() {
		return tid > -1;
	}

	public String getMd5() {
		return md5;
	}

	public void setMd5(String md5) {
		this.md5 = md5;
	}

	public int getObjectID() {
		return objectID;
	}

	public void setObjectID(int objectID) {
		this.objectID = objectID;
	}

	public int getGroupID() {
		return groupID;
	}

	public void setGroupID(int groupID) {
		this.groupID = groupID;
	}

	public int getEntryID() {
		return entryID;
	}

	public void setEntryID(int entryID) {
		this.entryID = entryID;
	}

	public int getFun() {
		return fun;
	}

	public void setFun(int fun) {
		this.fun = fun;
	}

	public int getInf() {
		return inf;
	}

	public int getInfoType() {
		return infoType;
	}

	public void setInfoType(int infoType) {
		this.infoType = infoType;
	}

	public int getPointNum() {
		return pointNum;
	}

	public void setPointNum(int pointNum) {
		this.pointNum = pointNum;
	}

	public int getReporttype() {
		return reporttype;
	}

	public void setReporttype(int reporttype) {
		this.reporttype = reporttype;
	}

	public String getAdiotype() {
		return adiotype;
	}

	public void setAdiotype(String adiotype) {
		this.adiotype = adiotype;
	}

	public void setInf(int inf) {
		this.inf = inf;
	}

	public float getRatio() {
		return ratio;
	}

	public void setRatio(float ratio) {
		this.ratio = ratio;
	}

	public int getBit() {
		return bit;
	}

	public void setBit(int bit) {
		this.bit = bit;
	}

	public String getBytes() {
		return bytes;
	}

	public void setBytes(String bytes) {
		this.bytes = bytes;
	}

	public int getLen() {
		return length;
	}

	public void setLen(int len) {
		this.length = len;
	}
	
	public String getType(){
		return dataType;
	}
	
	public void setType(String dataType) {
		this.dataType = dataType;
	}

	public float getThreshold() {
		return threshold;
	}

	public void setThreshold(float threshold) {
		this.threshold = threshold;
	}

	public int getObjId() {
		return objId;
	}

	public void setObjId(int objId) {
		this.objId = objId;
	}

	public int getUsed() {
		return used;
	}

	public void setUsed(int used) {
		this.used = used;
	}
	
	public boolean isDcaData() {
		return getLd()!=null || getObj()!=null 
				|| getGroup()!=null || getIed()!=null;
	}

}