package com.shrcn.tool.rtu.model;

// Generated 2012-2-9 14:04:24 by Hibernate Tools 3.2.2.GA

/**
 * TDpalogicied generated by hbm2java
 */
public class DcaDao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String name;
	private boolean select;
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public boolean isSelect() {
		return select;
	}
	public void setSelect(boolean select) {
		this.select = select;
	}
	
	
}