package com.shrcn.tool.rtu.model;

import java.util.HashSet;
import java.util.Set;

/**
 * TApplication generated by hbm2java
 */
public class DpaMasterDao  implements java.io.Serializable {

	/**
	 *  
	 */ 
	private static final long serialVersionUID = 1L;
	
     private String appName;
     private String masterName;
     private String tableName;
 	 private TApplication tapp;
	public String getAppName() {
		return appName;
	}
	public void setAppName(String appName) {
		this.appName = appName;
	}
	public String getMasterName() {
		return masterName;
	}
	public void setMasterName(String masterName) {
		this.masterName = masterName;
	}
	public String getTableName() {
		return tableName;
	}
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}
	public TApplication getTapp() {
		return tapp;
	}
	public void setTapp(TApplication tapp) {
		this.tapp = tapp;
	}
}


