package com.shrcn.tool.rtu.model;

import java.util.HashSet;
import java.util.Set;

/**
 * TApplication generated by hbm2java
 */
public class DpaTableDao  implements java.io.Serializable {

	/**
	 *  
	 */ 
	private static final long serialVersionUID = 1L;
	
     private String name;
     private String appName;
     private String type;
     private String data;
 	 private TDpalogicied dpalogicied;
     
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getData() {
		return data;
	}
	public void setData(String data) {
		this.data = data;
	}
	public TDpalogicied getDpalogicied() {
		return dpalogicied;
	}
	public void setDpalogicied(TDpalogicied dpalogicied) {
		this.dpalogicied = dpalogicied;
	}
	public String getAppName() {
		return appName;
	}
	public void setAppName(String appName) {
		this.appName = appName;
	}
}


