package com.shrcn.tool.rtu.model;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TAiexpr generated by hbm2java
 */
public class TAiexpr extends BaseCalcExpr {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public TAiexpr() {
	}

	public TAiexpr(int id) {
		super(id);
	}

	public TAiexpr(int id, String expression, int currentnumber,
			int totalnumber, TDcaMx mx, TDcaSt st, TDcaCo co, int saddr) {
		super(id, expression, currentnumber, totalnumber, mx, st, co, saddr);
	}

	@Override
	public BaseCalcExpr copy() {
		TAiexpr expr = new TAiexpr();
		assignValues(expr);
		return expr;
	}

}
