package com.shrcn.tool.rtu.model;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TAipoint generated by hbm2java
 */
public class TAipoint extends BaseDpaPoint {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String dividefactor;
	private String multifactor;
	private String offset;
	private String threshold;
	private String lowlimit;
	private String highlimit;
	private String di0;
	private String di1;
	private String infotype;
	private String thresholdPercent;
	private String timeTag;
	private String aitype;
	private String alias;

	public TAipoint() {
	}

	public TAipoint(int id) {
		super(id);
	}

	public String getDividefactor() {
		return this.dividefactor;
	}

	public void setDividefactor(String dividefactor) {
		this.dividefactor = dividefactor;
	}

	public String getMultifactor() {
		return this.multifactor;
	}

	public void setMultifactor(String multifactor) {
		this.multifactor = multifactor;
	}

	public String getOffset() {
		return this.offset;
	}

	public void setOffset(String offset) {
		this.offset = offset;
	}

	public String getThreshold() {
		return this.threshold;
	}

	public void setThreshold(String threshold) {
		this.threshold = threshold;
	}

	public String getLowlimit() {
		return this.lowlimit;
	}

	public void setLowlimit(String lowlimit) {
		this.lowlimit = lowlimit;
	}

	public String getHighlimit() {
		return this.highlimit;
	}

	public void setHighlimit(String highlimit) {
		this.highlimit = highlimit;
	}

	public String getDi0() {
		return this.di0;
	}

	public void setDi0(String di0) {
		this.di0 = di0;
	}

	public String getDi1() {
		return this.di1;
	}

	public void setDi1(String di1) {
		this.di1 = di1;
	}
	
	public String getInfotype() {
		return infotype;
	}

	public void setInfotype(String infotype) {
		this.infotype = infotype;
	}

	public String getThresholdPercent() {
		return thresholdPercent;
	}

	public void setThresholdPercent(String thresholdPercent) {
		this.thresholdPercent = thresholdPercent;
	}

	@Override
	public void setInfoType(int infoType) {
		// TODO Auto-generated method stub

	}

	@Override
	public void setPointNum(int pointNum) {
		// TODO Auto-generated method stub

	}

	public String getTimeTag() {
		return timeTag;
	}

	public void setTimeTag(String timeTag) {
		this.timeTag = timeTag;
	}

	public String getAitype() {
		return aitype;
	}

	public void setAitype(String aitype) {
		this.aitype = aitype;
	}

	public String getAlias() {
		return alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}
}
