package com.shrcn.tool.rtu.model;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TAopoint generated by hbm2java
 */
public class TAopoint extends BaseDpaPoint {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String controlmode;
	private String dividefactor;
	private String multifactor;
	private String offset;
	private String ontime;
	private String aetype;
	private String offtime;
	private String counttimes;
	private String pointattr;
	private String tabname;
	private String itemname;
	private String segdes;
	private String type;
	private String rw;
	private String associatedPoint;
	private String infotype;
	private String aotype;
	private int   overTime;
	
	public TAopoint() {
	}

	public TAopoint(int id) {
		super(id);
	}

	public String getControlmode() {
		return this.controlmode;
	}

	public void setControlmode(String controlmode) {
		this.controlmode = controlmode;
	}

	public String getDividefactor() {
		return this.dividefactor;
	}

	public void setDividefactor(String dividefactor) {
		this.dividefactor = dividefactor;
	}

	public String getMultifactor() {
		return this.multifactor;
	}

	public void setMultifactor(String multifactor) {
		this.multifactor = multifactor;
	}

	public String getAetype() {
		return aetype;
	}

	public void setAetype(String aetype) {
		this.aetype = aetype;
	}

	public String getOffset() {
		return this.offset;
	}

	public void setOffset(String offset) {
		this.offset = offset;
	}

	public String getOntime() {
		return ontime;
	}

	public void setOntime(String ontime) {
		this.ontime = ontime;
	}

	public String getOfftime() {
		return offtime;
	}

	public void setOfftime(String offtime) {
		this.offtime = offtime;
	}

	public String getCounttimes() {
		return counttimes;
	}

	public void setCounttimes(String counttimes) {
		this.counttimes = counttimes;
	}

	public String getPointattr() {
		return pointattr;
	}

	public void setPointattr(String pointattr) {
		this.pointattr = pointattr;
	}

	public String getTabname() {
		return tabname;
	}

	public void setTabname(String tabname) {
		this.tabname = tabname;
	}

	public String getItemname() {
		return itemname;
	}

	public void setItemname(String itemname) {
		this.itemname = itemname;
	}

	public String getSegdes() {
		return segdes;
	}

	public void setSegdes(String segdes) {
		this.segdes = segdes;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getRw() {
		return rw;
	}

	public void setRw(String rw) {
		this.rw = rw;
	}
	
	public String getAssociatedPoint() {
		return associatedPoint;
	}

	public void setAssociatedPoint(String associatedPoint) {
		this.associatedPoint = associatedPoint;
	}
	
	public String getInfotype() {
		return infotype;
	}

	public void setInfotype(String infotype) {
		this.infotype = infotype;
	}

	@Override
	public void setInfoType(int infoType) {
		// TODO Auto-generated method stub

	}

	@Override
	public void setPointNum(int pointNum) {
		// TODO Auto-generated method stub

	}

	public String getAotype() {
		return aotype;
	}

	public void setAotype(String aotype) {
		this.aotype = aotype;
	}

	public int getOverTime() {
		return overTime;
	}

	public void setOverTime(int overTime) {
		this.overTime = overTime;
	}
}
