package com.shrcn.tool.rtu.model;

import java.util.HashSet;
import java.util.Set;

/**
 * TApptype generated by hbm2java
 */
public class TApptype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int id;
	private String applicationname;
	private String desc;
	private Set<TProperty> properties = new HashSet<TProperty>();

	public TApptype() {
	}

	public TApptype(int id) {
		this.id = id;
	}

	public TApptype(int id, String applicationname, String desc) {
		this.id = id;
		this.applicationname = applicationname;
		this.desc = desc;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getApplicationname() {
		return this.applicationname;
	}

	public void setApplicationname(String applicationname) {
		this.applicationname = applicationname;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public Set<TProperty> getProperties() {
		return properties;
	}

	public void setProperties(Set<TProperty> properties) {
		this.properties = properties;
	}
	
	/**
	 * 获取指定属性。
	 * @param property
	 * @return
	 */
	public TProperty getProperty(String property) {
		for (TProperty pv : getProperties()) {
			if (property.equals(pv.getName())) {
				return pv;
			}
		}
		return null;
	}
	
	/**
	 * 获取指定属性值。
	 * @param property
	 * @return
	 */
	public String geTProperty(String property) {
		TProperty pv = getProperty(property);
		if (pv == null)
			return null;
		return pv.getDefaultvalue();
	}
}
