package com.shrcn.tool.rtu.model;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TCipoint generated by hbm2java
 */
public class TCipoint extends BaseDpaPoint {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String pointmode;
	private String reportflag;
	private String dividefactor;
	private String multifactor;

	public TCipoint() {
	}

	public TCipoint(int id) {
		super(id);
	}

	public String getPointmode() {
		return this.pointmode;
	}

	public void setPointmode(String pointmode) {
		this.pointmode = pointmode;
	}

	public String getReportflag() {
		return this.reportflag;
	}

	public void setReportflag(String reportflag) {
		this.reportflag = reportflag;
	}

	public String getDividefactor() {
		return dividefactor;
	}

	public void setDividefactor(String dividefactor) {
		this.dividefactor = dividefactor;
	}

	public String getMultifactor() {
		return this.multifactor;
	}

	public void setMultifactor(String multifactor) {
		this.multifactor = multifactor;
	}

	@Override
	public void setInfoType(int infoType) {
		// TODO Auto-generated method stub

	}

	@Override
	public void setPointNum(int pointNum) {
		// TODO Auto-generated method stub

	}

}
