package com.shrcn.tool.rtu.model;

import java.util.HashSet;
import java.util.Set;

/**
 * TApplication generated by hbm2java
 */
public class TCollection  implements java.io.Serializable {

	/**
	 *  
	 */ 
	private static final long serialVersionUID = 1L;
	
     private int id;
     private String iedName;
     private String name;
     private String addressA;
 	 private String addressB;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getIedName() {
		return iedName;
	}
	public void setIedName(String iedName) {
		this.iedName = iedName;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getAddressA() {
		return addressA;
	}
	public void setAddressA(String addressA) {
		this.addressA = addressA;
	}
	public String getAddressB() {
		return addressB;
	}
	public void setAddressB(String addressB) {
		this.addressB = addressB;
	}
 	 
}


