package com.shrcn.tool.rtu.model;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TComchannel generated by hbm2java
 */
public class TComchannel extends BaseDpaChannel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String portname;
	private String baudrate;
	private String databit;
	private String stopbit;
	private String parity;
	private String maxframelength;
	private String singleacksupported;
	private String standbystartdelay;
	private String maxfcbcount;
	private String linkaddrlength;
	private String linkaddress;
	private String clearcos;
	private String clearsoe;
	private String servicelist;
	private String infotype13;
	// DISA
	private String txtimeout;
	private String rxtimeout;
	private String synchead;
	private String remoteaddress;
	// 101
	private String iec101type = "2";
	// 103COM
	private String manuid = "1";

	private int statusPoint;

	// 103com所有
	private String comType;
	private String localAddr;
	private String tmTran;
	private String tmRecv;
	private String bufferSize;
	private String respTimeout;
	private String procType;
	
	public TComchannel() {
	}

	public TComchannel(int id) {
		super(id);
	}

	public String getPortname() {
		return this.portname;
	}

	public void setPortname(String portname) {
		this.portname = portname;
	}

	public String getBaudrate() {
		return baudrate;
	}

	public void setBaudrate(String baudrate) {
		this.baudrate = baudrate;
	}

	public String getDatabit() {
		return databit;
	}

	public void setDatabit(String databit) {
		this.databit = databit;
	}

	public String getStopbit() {
		return stopbit;
	}

	public void setStopbit(String stopbit) {
		this.stopbit = stopbit;
	}

	public String getParity() {
		return parity;
	}

	public void setParity(String parity) {
		this.parity = parity;
	}

	public String getMaxframelength() {
		return maxframelength;
	}

	public void setMaxframelength(String maxframelength) {
		this.maxframelength = maxframelength;
	}

	public String getSingleacksupported() {
		return singleacksupported;
	}

	public void setSingleacksupported(String singleacksupported) {
		this.singleacksupported = singleacksupported;
	}

	public String getStandbystartdelay() {
		return standbystartdelay;
	}

	public void setStandbystartdelay(String standbystartdelay) {
		this.standbystartdelay = standbystartdelay;
	}

	public String getMaxfcbcount() {
		return maxfcbcount;
	}

	public void setMaxfcbcount(String maxfcbcount) {
		this.maxfcbcount = maxfcbcount;
	}

	public String getLinkaddrlength() {
		return linkaddrlength;
	}

	public void setLinkaddrlength(String linkaddrlength) {
		this.linkaddrlength = linkaddrlength;
	}

	public String getLinkaddress() {
		return linkaddress;
	}

	public void setLinkaddress(String linkaddress) {
		this.linkaddress = linkaddress;
	}

	public String getClearcos() {
		return clearcos;
	}

	public void setClearcos(String clearcos) {
		this.clearcos = clearcos;
	}

	public String getClearsoe() {
		return clearsoe;
	}

	public void setClearsoe(String clearsoe) {
		this.clearsoe = clearsoe;
	}

	public String getServicelist() {
		return servicelist;
	}

	public void setServicelist(String servicelist) {
		this.servicelist = servicelist;
	}

	public String getInfotype13() {
		return infotype13;
	}

	public void setInfotype13(String infotype13) {
		this.infotype13 = infotype13;
	}

	public String getTxtimeout() {
		return txtimeout;
	}

	public void setTxtimeout(String txtimeout) {
		this.txtimeout = txtimeout;
	}

	public String getRxtimeout() {
		return rxtimeout;
	}

	public void setRxtimeout(String rxtimeout) {
		this.rxtimeout = rxtimeout;
	}

	public String getSynchead() {
		return synchead;
	}

	public void setSynchead(String synchead) {
		this.synchead = synchead;
	}

	public String getRemoteaddress() {
		return remoteaddress;
	}

	public void setRemoteaddress(String remoteaddress) {
		this.remoteaddress = remoteaddress;
	}

	public String getIec101type() {
		return iec101type;
	}

	public void setIec101type(String iec101type) {
		this.iec101type = iec101type;
	}

	public String getManuid() {
		return manuid;
	}

	public void setManuid(String manuid) {
		this.manuid = manuid;
	}

	public int getStatusPoint() {
		return statusPoint;
	}

	public void setStatusPoint(int statusPoint) {
		this.statusPoint = statusPoint;
	}

	public String getComType() {
		return comType;
	}

	public void setComType(String comType) {
		this.comType = comType;
	}

	public String getLocalAddr() {
		return localAddr;
	}

	public void setLocalAddr(String localAddr) {
		this.localAddr = localAddr;
	}

	public String getTmTran() {
		return tmTran;
	}

	public void setTmTran(String tmTran) {
		this.tmTran = tmTran;
	}

	public String getTmRecv() {
		return tmRecv;
	}

	public void setTmRecv(String tmRecv) {
		this.tmRecv = tmRecv;
	}

	public String getBufferSize() {
		return bufferSize;
	}

	public void setBufferSize(String bufferSize) {
		this.bufferSize = bufferSize;
	}

	public String getRespTimeout() {
		return respTimeout;
	}

	public void setRespTimeout(String respTimeout) {
		this.respTimeout = respTimeout;
	}

	public String getProcType() {
		return procType;
	}

	public void setProcType(String procType) {
		this.procType = procType;
	}
}