package com.shrcn.tool.rtu.model;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TDcaSp generated by hbm2java
 */
public class TDcaSp extends BaseDcaPoint {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public TDcaSp() {
		super();
	}

	public TDcaSp(int id) {
		super(id);
	}

	public TDcaSp(int id, String ref, int subzone, int sharednums) {
		super(id, ref, subzone, sharednums);
	}
}
