package com.shrcn.tool.rtu.model;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TDcaSe generated by hbm2java
 */
public class TDcaSe extends BaseDcaPoint {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String dividefactor;
	private String multifactor;
	private String offset;

	public TDcaSe() {
	}
	
	public TDcaSe(int id) {
		super(id);
	}

	public TDcaSe(int id, String ref, int subzone, int sharednums,
			String dividefactor, String multifactor, String offset) {
		super(id, ref, subzone, sharednums);
		this.dividefactor = dividefactor;
		this.multifactor = multifactor;
		this.offset = offset;
	}

	public String getDividefactor() {
		return this.dividefactor;
	}

	public void setDividefactor(String dividefactor) {
		this.dividefactor = dividefactor;
	}

	public String getMultifactor() {
		return this.multifactor;
	}

	public void setMultifactor(String multifactor) {
		this.multifactor = multifactor;
	}

	public String getOffset() {
		return this.offset;
	}

	public void setOffset(String offset) {
		this.offset = offset;
	}
}
