package com.shrcn.tool.rtu.model;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TDcarcb generated by hbm2java
 */
public class TDcarcb implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int id;
	private String rptref;
	private int intgpd;
	private String dchg;
	private String qchg;
	private String dupd;
	private String integrity;
	private String gi;
	private String indexed;
	private String index;
	private int max;
	private String   optFlds;
	private int IEDType;
	
	private TDcaied ied;

	public TDcarcb() {
	}

	public TDcarcb(int id) {
		this.id = id;
	}

	public TDcarcb(int id, String rptref, int intgpd, String dchg, String qchg,
			String dupd, String integrity, String gi, String indexed,
			String index) {
		this.id = id;
		this.rptref = rptref;
		this.intgpd = intgpd;
		this.dchg = dchg;
		this.qchg = qchg;
		this.dupd = dupd;
		this.integrity = integrity;
		this.gi = gi;
		this.indexed = indexed;
		this.index = index;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getRptref() {
		return this.rptref;
	}

	public void setRptref(String rptref) {
		this.rptref = rptref;
	}

	public int getIntgpd() {
		return this.intgpd;
	}

	public void setIntgpd(int intgpd) {
		this.intgpd = intgpd;
	}

	public String getDchg() {
		return this.dchg;
	}

	public void setDchg(String dchg) {
		this.dchg = dchg;
	}

	public String getQchg() {
		return this.qchg;
	}

	public void setQchg(String qchg) {
		this.qchg = qchg;
	}

	public String getDupd() {
		return this.dupd;
	}

	public void setDupd(String dupd) {
		this.dupd = dupd;
	}

	public String getIntegrity() {
		return this.integrity;
	}

	public void setIntegrity(String integrity) {
		this.integrity = integrity;
	}

	public String getGi() {
		return this.gi;
	}

	public void setGi(String gi) {
		this.gi = gi;
	}

	public String getIndexed() {
		return this.indexed;
	}

	public void setIndexed(String indexed) {
		this.indexed = indexed;
	}

	public String getIndex() {
		return this.index;
	}

	public void setIndex(String index) {
		this.index = index;
	}

	public TDcaied getIed() {
		return ied;
	}

	public void setIed(TDcaied ied) {
		this.ied = ied;
	}

	public int getMax() {
		return max;
	}

	public void setMax(int max) {
		this.max = max;
	}

	public String getOptFlds() {
		return optFlds;
	}

	public void setOptFlds(String optFlds) {
		this.optFlds = optFlds;
	}

	public int getIEDType() {
		return IEDType;
	}

	public void setIEDType(int iEDType) {
		IEDType = iEDType;
	}
	
}
