package com.shrcn.tool.rtu.model;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TDcaMx generated by hbm2java
 */
public class TDcaMx extends BaseDcaPoint {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String dividefactor;
	private String multifactor;
	private String offset;
	private String lowLimit;
	private String highLimit;
	/** Answer采集 **/
	private String calExp;

	public TDcaMx() {
	}
	
	public TDcaMx(int id, int dcaindex, int objId, int saddr,
			String desc, String fc, int objectID, int entryID, int pointNum,
			float ratio, String bytes, int bit, String type, int length,
			float threshold) {
		super(id, dcaindex, objId, saddr, desc, fc, objectID, entryID,
				pointNum, ratio, bytes, bit, type, length, threshold);
	}

	public TDcaMx(int id) {
		super(id);
	}

	public TDcaMx(int id, String ref, int subzone, int sharednums,
			String dividefactor, String multifactor, String offset) {
		super(id, ref, subzone, sharednums);
		this.dividefactor = dividefactor;
		this.multifactor = multifactor;
		this.offset = offset;
	}

	public String getDividefactor() {
		return this.dividefactor;
	}

	public void setDividefactor(String dividefactor) {
		this.dividefactor = dividefactor;
	}

	public String getMultifactor() {
		return this.multifactor;
	}

	public void setMultifactor(String multifactor) {
		this.multifactor = multifactor;
	}

	public String getOffset() {
		return this.offset;
	}

	public void setOffset(String offset) {
		this.offset = offset;
	}

	public String getLowLimit() {
		return lowLimit;
	}

	public void setLowLimit(String lowLimit) {
		this.lowLimit = lowLimit;
	}

	public String getHighLimit() {
		return highLimit;
	}

	public void setHighLimit(String highLimit) {
		this.highLimit = highLimit;
	}

	public String getCalExp() {
		return calExp;
	}

	public void setCalExp(String calExp) {
		this.calExp = calExp;
	}

//	public String getCalExp() {
//		return calExp;
//	}
//
//	public void setCalExp(String calExp) {
//		this.calExp = calExp;
//	}
}
