package com.shrcn.tool.rtu.model;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TDcaSg generated by hbm2java
 */
public class TDcaSg extends BaseDcaPoint {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String dividefactor;
	private String multifactor;
	private String offset;
	private String ctlmode;
	private String calExp;

	public TDcaSg() {
	}
	
	public TDcaSg(int id, int dcaindex, int objId, int saddr,
			String desc, String fc, int objectID, int entryID, int pointNum,
			float ratio, String bytes, int bit, String type, int length) {
		super(id, dcaindex, objId, saddr, desc, fc, objectID, entryID,
				pointNum, ratio, bytes, bit, type, length);
	}

	public TDcaSg(int id) {
		super(id);
	}

	public TDcaSg(int id, String ref, int subzone, int sharednums,
			String dividefactor, String multifactor, String offset) {
		super(id, ref, subzone, sharednums);
		this.dividefactor = dividefactor;
		this.multifactor = multifactor;
		this.offset = offset;
	}

	public String getCtlmode() {
		return this.ctlmode;
	}

	public void setCtlmode(String ctlmode) {
		this.ctlmode = ctlmode;
	}

	public String getDividefactor() {
		return this.dividefactor;
	}

	public void setDividefactor(String dividefactor) {
		this.dividefactor = dividefactor;
	}

	public String getMultifactor() {
		return this.multifactor;
	}

	public void setMultifactor(String multifactor) {
		this.multifactor = multifactor;
	}

	public String getOffset() {
		return this.offset;
	}

	public void setOffset(String offset) {
		this.offset = offset;
	}

	public TDcaSe getDcaSe() {
		TDcaSe p = new TDcaSe();
		assignBaseValues(p);
		if (getRef() != null) {
			p.setRef(getRef().replace("$SG$", "$SE$"));
		}
		p.setFc("SE");
		p.setDividefactor(getDividefactor());
		p.setMultifactor(getMultifactor());
		p.setOffset(getOffset());
		return p;
	}
	/**
	 * 拷贝SE点，仅用于Modbus采集。
	 * @return
	 */
	public TDcaSe getDcaSeForMb() {
		TDcaSe p = new TDcaSe();
		assignBaseValues(p);
		p.setFc("SE");
		return p;
	}

	public String getCalExp() {
		return calExp;
	}

	public void setCalExp(String calExp) {
		this.calExp = calExp;
	}
}
