package com.shrcn.tool.rtu.model;

import java.util.HashSet;
import java.util.Set;

/**
 * TDca generated by hbm2java
 */
public class TDca implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5143703484417944330L;

	private int id;
	private int dcaIndex;
	private int iedNumber;
	private int iedOffset;
    private int statusPointOfGUI;
   
    private int wfskType;
    private int isSgpotWfsk;

    // modbus 通道类型（1表示网络，2表示串口）
    private int dcaType;

	private TApplication app;

	private Set<BaseDcaied> ieds = new HashSet<BaseDcaied>();
	private Set<TDcaCom> coms = new HashSet<TDcaCom>();
	private Set<TDcaNet> nets = new HashSet<TDcaNet>();

	public TDca(){}
	
	public TDca(int id) {
		this.id = id;
	}


	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}


	public TApplication getApp() {
		return app;
	}

	public void setApp(TApplication app) {
		this.app = app;
	}

	public int getDcaIndex() {
		return dcaIndex;
	}

	public void setDcaIndex(int dcaIndex) {
		this.dcaIndex = dcaIndex;
	}

	public int getIedNumber() {
		return iedNumber;
	}

	public void setIedNumber(int iedNumber) {
		this.iedNumber = iedNumber;
	}

	public int getIedOffset() {
		return iedOffset;
	}

	public void setIedOffset(int iedOffset) {
		this.iedOffset = iedOffset;
	}

	public Set<TDcaCom> getComs() {
		return coms;
	}

	public void setComs(Set<TDcaCom> coms) {
		this.coms = coms;
	}

	public void addCom(TDcaCom com) {
		getComs().add(com);
		com.setDca(this);
	}

	public Set<TDcaNet> getNets() {
		return nets;
	}

	public void setNets(Set<TDcaNet> nets) {
		this.nets = nets;
	}

	public void addNet(TDcaNet net) {
		getNets().add(net);
		net.setDca(this);
	}

	public Set<BaseDcaied> getIeds() {
		return ieds;
	}

	public void setIeds(Set<BaseDcaied> ieds) {
		this.ieds = ieds;
	}
	
	public void addIed(BaseDcaied ied) {
		getIeds().add(ied);
		ied.setDca(this);
	}

	public int getStatusPointOfGUI() {
		return statusPointOfGUI;
	}

	public void setStatusPointOfGUI(int statusPointOfGUI) {
		this.statusPointOfGUI = statusPointOfGUI;
	}

	public int getWfskType() {
		return wfskType;
	}

	public void setWfskType(int wfskType) {
		this.wfskType = wfskType;
	}

	public int getIsSgpotWfsk() {
		return isSgpotWfsk;
	}

	public void setIsSgpotWfsk(int isSgpotWfsk) {
		this.isSgpotWfsk = isSgpotWfsk;
	}

	public int getDcaType() {
		return dcaType;
	}

	public void setDcaType(int dcaType) {
		this.dcaType = dcaType;
	}
}
