package com.shrcn.tool.rtu.model;

import java.util.HashSet;
import java.util.Set;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TDcaied generated by hbm2java
 */
public class TDcaied extends BaseDcaied implements java.io.Serializable {

	private static final long serialVersionUID = 5702500169911777652L;
	
	private int autoconninterval;
	private int resptimeout;
	private int cmdtermtimeout;
	private int autogiinterval;
	private int ldoffset;
	private int ldnumber;
	private int rcboffset;
	private int rcbnumber;
	private int statuspointA;//双网通信状态点
	private int statuspointB;//双网通信状态点
    private String netAIpAddress;
    private String netBIpAddress;
    
    private String urcbtime;
    private String brcbtime;
    private String BRCBOptFlds;
    private String URCBOptFlds;
    private String brcbtrg;
    private String urcbtrg;
    
    private int RCDMadePoint;
    private String RCDMadePath;
	
	private Set<TDcald> lds = new HashSet<TDcald>();
	private Set<TDcarcb> rcbs = new HashSet<TDcarcb>();

	public TDcaied() {
		super();
		netAIpAddress= "0.0.0.0";
		netBIpAddress= "0.0.0.0";
	}
	
	public TDcaied(int id) {
		super(id);
	}
	
	public TDcaied(int id, String iedname, int statuspoint, int statuspointB, int ldoffset,
			int ldnumber, int rcboffset, int rcbnumber, int autoconninterval,
			int resptimeout, int cmdtermtimeout, int autogiinterval) {
		setId(id);
		setIedname(iedname);
		setStatuspoint(statuspoint);
		this.statuspointB = statuspointB;
		this.ldoffset = ldoffset;
		this.ldnumber = ldnumber;
		this.rcboffset = rcboffset;
		this.rcbnumber = rcbnumber;
		this.autoconninterval = autoconninterval;
		this.resptimeout = resptimeout;
		this.cmdtermtimeout = cmdtermtimeout;
		this.autogiinterval = autogiinterval;
	}

	public int getLdoffset() {
		return this.ldoffset;
	}

	public void setLdoffset(int ldoffset) {
		this.ldoffset = ldoffset;
	}

	public int getLdnumber() {
		return this.ldnumber;
	}

	public void setLdnumber(int ldnumber) {
		this.ldnumber = ldnumber;
	}

	public int getRcboffset() {
		return this.rcboffset;
	}

	public void setRcboffset(int rcboffset) {
		this.rcboffset = rcboffset;
	}

	public int getRcbnumber() {
		return this.rcbnumber;
	}

	public void setRcbnumber(int rcbnumber) {
		this.rcbnumber = rcbnumber;
	}

	public int getAutoconninterval() {
		return this.autoconninterval;
	}

	public void setAutoconninterval(int autoconninterval) {
		this.autoconninterval = autoconninterval;
	}

	public int getResptimeout() {
		return this.resptimeout;
	}

	public void setResptimeout(int resptimeout) {
		this.resptimeout = resptimeout;
	}

	public int getCmdtermtimeout() {
		return this.cmdtermtimeout;
	}

	public void setCmdtermtimeout(int cmdtermtimeout) {
		this.cmdtermtimeout = cmdtermtimeout;
	}

	public int getAutogiinterval() {
		return this.autogiinterval;
	}

	public void setAutogiinterval(int autogiinterval) {
		this.autogiinterval = autogiinterval;
	}

	public Set<TDcald> getLds() {
		return lds;
	}

	public void setLds(Set<TDcald> lds) {
		this.lds = lds;
	}

	public void addLd(TDcald ld) {
		getLds().add(ld);
		ld.setIed(this);
	}

	public Set<TDcarcb> getRcbs() {
		return rcbs;
	}

	public void setRcbs(Set<TDcarcb> rcbs) {
		this.rcbs = rcbs;
	}

	public void addRcb(TDcarcb rcb) {
		getRcbs().add(rcb);
		rcb.setIed(this);
	}
	
	public int getStatuspointA() {
		return statuspointA;
	}

	public void setStatuspointA(int statuspointA) {
		this.statuspointA = statuspointA;
	}

	public int getStatuspointB() {
		return statuspointB;
	}

	public void setStatuspointB(int statuspointB) {
		this.statuspointB = statuspointB;
	}

	public String getNetAIpAddress() {
		return netAIpAddress;
	}

	public void setNetAIpAddress(String netAIpAddress) {
		this.netAIpAddress = netAIpAddress;
	}

	public String getNetBIpAddress() {
		return netBIpAddress;
	}

	public void setNetBIpAddress(String netBIpAddress) {
		this.netBIpAddress = netBIpAddress;
	}

	public String getBRCBOptFlds() {
		return BRCBOptFlds;
	}

	public void setBRCBOptFlds(String bRCBOptFlds) {
		BRCBOptFlds = bRCBOptFlds;
	}

	public String getURCBOptFlds() {
		return URCBOptFlds;
	}

	public void setURCBOptFlds(String uRCBOptFlds) {
		URCBOptFlds = uRCBOptFlds;
	}

	public String getUrcbtime() {
		return urcbtime;
	}

	public void setUrcbtime(String urcbtime) {
		this.urcbtime = urcbtime;
	}

	public String getBrcbtime() {
		return brcbtime;
	}

	public void setBrcbtime(String brcbtime) {
		this.brcbtime = brcbtime;
	}

	public String getBrcbtrg() {
		return brcbtrg;
	}

	public void setBrcbtrg(String brcbtrg) {
		this.brcbtrg = brcbtrg;
	}

	public String getUrcbtrg() {
		return urcbtrg;
	}

	public void setUrcbtrg(String urcbtrg) {
		this.urcbtrg = urcbtrg;
	}

	public int getRCDMadePoint() {
		return RCDMadePoint;
	}

	public void setRCDMadePoint(int rcdMadePoint) {
		RCDMadePoint = rcdMadePoint;
	}

	public String getRCDMadePath() {
		return RCDMadePath;
	}

	public void setRCDMadePath(String rcdMadePath) {
		RCDMadePath = rcdMadePath;
	}
	
}
