package com.shrcn.tool.rtu.model;

import java.util.HashSet;
import java.util.Set;

/**
 * TDcald generated by hbm2java
 */
public class TDcald implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int id;
	private String ldname;
	private String inst;
	private int mxnumber;
	private int stnumber;
	private int conumber;
	private int spnumber;
	private int sgnumber;
	private int senumber;
	private int mxoffset;
	private int stoffset;
	private int cooffset;
	private int spoffset;
	private int sgoffset;
	private int seoffset;

	private TDcaied ied;
	private Set<TDcaMx> psMx = new HashSet<TDcaMx>();
	private Set<TDcaSt> psSt = new HashSet<TDcaSt>();
	private Set<TDcaCo> psCo = new HashSet<TDcaCo>();
	private Set<TDcaSp> psSp = new HashSet<TDcaSp>();
	private Set<TDcaSg> psSg = new HashSet<TDcaSg>();
	private Set<TDcaSe> psSe = new HashSet<TDcaSe>();

	public TDcald() {
	}

	public TDcald(int id) {
		this.id = id;
	}

	public TDcald(int id, String ldname, int mxnumber, int stnumber,
			int conumber, int spnumber, int sgnumber, int senumber,
			int mxoffset, int stoffset, int cooffset, int spoffset,
			int sgoffset, int seoffset) {
		this.id = id;
		this.ldname = ldname;
		this.mxnumber = mxnumber;
		this.stnumber = stnumber;
		this.conumber = conumber;
		this.spnumber = spnumber;
		this.sgnumber = sgnumber;
		this.senumber = senumber;
		this.mxoffset = mxoffset;
		this.stoffset = stoffset;
		this.cooffset = cooffset;
		this.spoffset = spoffset;
		this.sgoffset = sgoffset;
		this.seoffset = seoffset;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLdname() {
		return this.ldname;
	}

	public void setLdname(String ldname) {
		this.ldname = ldname;
	}

	public String getInst() {
		return inst;
	}

	public void setInst(String inst) {
		this.inst = inst;
	}

	public int getMxnumber() {
		return this.mxnumber;
	}

	public void setMxnumber(int mxnumber) {
		this.mxnumber = mxnumber;
	}

	public int getStnumber() {
		return this.stnumber;
	}

	public void setStnumber(int stnumber) {
		this.stnumber = stnumber;
	}

	public int getConumber() {
		return this.conumber;
	}

	public void setConumber(int conumber) {
		this.conumber = conumber;
	}

	public int getSpnumber() {
		return this.spnumber;
	}

	public void setSpnumber(int spnumber) {
		this.spnumber = spnumber;
	}

	public int getSgnumber() {
		return this.sgnumber;
	}

	public void setSgnumber(int sgnumber) {
		this.sgnumber = sgnumber;
	}

	public int getSenumber() {
		return this.senumber;
	}

	public void setSenumber(int senumber) {
		this.senumber = senumber;
	}

	public int getMxoffset() {
		return this.mxoffset;
	}

	public void setMxoffset(int mxoffset) {
		this.mxoffset = mxoffset;
	}

	public int getStoffset() {
		return this.stoffset;
	}

	public void setStoffset(int stoffset) {
		this.stoffset = stoffset;
	}

	public int getCooffset() {
		return this.cooffset;
	}

	public void setCooffset(int cooffset) {
		this.cooffset = cooffset;
	}

	public int getSpoffset() {
		return this.spoffset;
	}

	public void setSpoffset(int spoffset) {
		this.spoffset = spoffset;
	}

	public int getSgoffset() {
		return this.sgoffset;
	}

	public void setSgoffset(int sgoffset) {
		this.sgoffset = sgoffset;
	}

	public int getSeoffset() {
		return this.seoffset;
	}

	public void setSeoffset(int seoffset) {
		this.seoffset = seoffset;
	}

	public TDcaied getIed() {
		return ied;
	}

	public void setIed(TDcaied ied) {
		this.ied = ied;
	}

	public Set<TDcaMx> getPsMx() {
		return psMx;
	}

	public void setPsMx(Set<TDcaMx> psMx) {
		this.psMx = psMx;
	}

	public Set<TDcaSt> getPsSt() {
		return psSt;
	}

	public void setPsSt(Set<TDcaSt> psSt) {
		this.psSt = psSt;
	}

	public Set<TDcaCo> getPsCo() {
		return psCo;
	}

	public void setPsCo(Set<TDcaCo> psCo) {
		this.psCo = psCo;
	}

	public Set<TDcaSp> getPsSp() {
		return psSp;
	}

	public void setPsSp(Set<TDcaSp> psSp) {
		this.psSp = psSp;
	}

	public Set<TDcaSg> getPsSg() {
		return psSg;
	}

	public void setPsSg(Set<TDcaSg> psSg) {
		this.psSg = psSg;
	}

	public Set<TDcaSe> getPsSe() {
		return psSe;
	}

	public void setPsSe(Set<TDcaSe> psSe) {
		this.psSe = psSe;
	}

	public void addMxPoint(TDcaMx pmx) {
		getPsMx().add(pmx);
		pmx.setLd(this);
	}

	public void addStPoint(TDcaSt pst) {
		getPsSt().add(pst);
		pst.setLd(this);
	}

	public void addCoPoint(TDcaCo pco) {
		getPsCo().add(pco);
		pco.setLd(this);
	}

	public void addSpPoint(TDcaSp psp) {
		getPsSp().add(psp);
		psp.setLd(this);
	}

	public void addSgPoint(TDcaSg psg) {
		getPsSg().add(psg);
		psg.setLd(this);
	}

	public void addSePoint(TDcaSe pse) {
		getPsSe().add(pse);
		pse.setLd(this);
	}

	public int getTotalNumber() {
		return mxnumber + stnumber + conumber + spnumber + sgnumber + senumber;
	}
}