package com.shrcn.tool.rtu.model;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TDoexpr generated by hbm2java
 */
public class TDoexpr extends BaseCalcExpr {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String pointattr;
	private String valueattr;
	private String optname;
	private String bayoid;
	private String baystate;
	private String exemode;

	public TDoexpr() {
	}

	public TDoexpr(int id) {
		super(id);
	}

	public TDoexpr(int id, String expression, int currentnumber,
			int totalnumber, TDcaMx mx, TDcaSt st, TDcaCo co, int saddr) {
		super(id, expression, currentnumber, totalnumber, mx, st, co, saddr);
	}

	public String getOptname() {
		return this.optname;
	}

	public void setOptname(String optname) {
		this.optname = optname;
	}

	public String getBayoid() {
		return this.bayoid;
	}

	public void setBayoid(String bayoid) {
		this.bayoid = bayoid;
	}

	public String getPointattr() {
		return pointattr;
	}

	public void setPointattr(String pointattr) {
		this.pointattr = pointattr;
	}

	public String getValueattr() {
		return valueattr;
	}

	public void setValueattr(String valueattr) {
		this.valueattr = valueattr;
	}

	public String getBaystate() {
		return baystate;
	}

	public void setBaystate(String baystate) {
		this.baystate = baystate;
	}

	public String getExemode() {
		return exemode;
	}

	public void setExemode(String exemode) {
		this.exemode = exemode;
	}

	@Override
	public BaseCalcExpr copy() {
		TDoexpr expr = new TDoexpr();
		assignValues(expr);
		expr.setPointattr(pointattr);
		expr.setValueattr(valueattr);
		expr.setOptname(optname);
		expr.setBayoid(bayoid);
		expr.setBaystate(baystate);
		expr.setExemode(exemode);
		return expr;
	}

}
