package com.shrcn.tool.rtu.model;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TDopoint generated by hbm2java
 */
public class TDopoint extends BaseDpaPoint {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String pointmode;
	private String ontime;
	private String offtime;
	private String counttimes;
	private String controlmode;
	private String pointattr;
	private String fun;
	private String inf;

	private int pointNum;
	private String infoType;
	private String associatedLockPoint;
	private String associatedLockSate;
	private String dotype;
	private int overTime;
	
	public TDopoint() {
	}

	public TDopoint(int id) {
		super(id);
	}

	public String getPointmode() {
		return this.pointmode;
	}

	public void setPointmode(String pointmode) {
		this.pointmode = pointmode;
	}

	public String getOntime() {
		return this.ontime;
	}

	public void setOntime(String ontime) {
		this.ontime = ontime;
	}

	public String getOfftime() {
		return this.offtime;
	}

	public void setOfftime(String offtime) {
		this.offtime = offtime;
	}

	public String getCounttimes() {
		return this.counttimes;
	}

	public void setCounttimes(String counttimes) {
		this.counttimes = counttimes;
	}

	public String getControlmode() {
		return this.controlmode;
	}

	public void setControlmode(String controlmode) {
		this.controlmode = controlmode;
	}

	public String getPointattr() {
		return this.pointattr;
	}

	public void setPointattr(String pointattr) {
		this.pointattr = pointattr;
	}

	public String getFun() {
		return fun;
	}

	public void setFun(String fun) {
		this.fun = fun;
	}

	public String getInf() {
		return inf;
	}

	public void setInf(String inf) {
		this.inf = inf;
	}

	public int getPointNum() {
		return pointNum;
	}

	public void setPointNum(int pointNum) {
		this.pointNum = pointNum;
	}

	public String getAssociatedLockPoint() {
		return associatedLockPoint;
	}

	public void setAssociatedLockPoint(String associatedLockPoint) {
		this.associatedLockPoint = associatedLockPoint;
	}

	public String getAssociatedLockSate() {
		return associatedLockSate;
	}

	public void setAssociatedLockSate(String associatedLockSate) {
		this.associatedLockSate = associatedLockSate;
	}

	public void setInfoType(String infoType) {
		this.infoType = infoType;
	}

	public String getInfoType() {
		return infoType;
	}

	public String getDotype() {
		return dotype;
	}

	public void setDotype(String dotype) {
		this.dotype = dotype;
	}

	@Override
	public void setInfoType(int infoType) {
		
	}

	public int getOverTime() {
		return overTime;
	}

	public void setOverTime(int overTime) {
		this.overTime = overTime;
	}

}
