package com.shrcn.tool.rtu.model;

import java.util.HashSet;
import java.util.Set;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TDpamaster generated by hbm2java
 */
public class TDpamaster implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int id;
	private String name;
	private int iednumber;
	private int iedoffset;
	private int netnumber;
	private int netoffset;
	private int comnumber;
	private int comoffset;

	private TApplication app;
	private Set<TDpalogicied> logicieds = new HashSet<TDpalogicied>();

	public TDpamaster() {
	}
	
	public TDpamaster(int id, int iednumber, int iedoffset, int netnumber,
			int netoffset) {
		super();
		this.id = id;
		this.iednumber = iednumber;
		this.iedoffset = iedoffset;
		this.netnumber = netnumber;
		this.netoffset = netoffset;
	}

	public TDpamaster(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getIednumber() {
		return this.iednumber;
	}

	public void setIednumber(int iednumber) {
		this.iednumber = iednumber;
	}

	public int getIedoffset() {
		return this.iedoffset;
	}

	public void setIedoffset(int iedoffset) {
		this.iedoffset = iedoffset;
	}

	public int getNetnumber() {
		return netnumber;
	}

	public void setNetnumber(int netnumber) {
		this.netnumber = netnumber;
	}

	public int getNetoffset() {
		return netoffset;
	}

	public void setNetoffset(int netoffset) {
		this.netoffset = netoffset;
	}

	public int getComnumber() {
		return comnumber;
	}

	public void setComnumber(int comnumber) {
		this.comnumber = comnumber;
	}

	public int getComoffset() {
		return comoffset;
	}

	public void setComoffset(int comoffset) {
		this.comoffset = comoffset;
	}

	public TApplication getApp() {
		return app;
	}

	public void setApp(TApplication app) {
		this.app = app;
	}

	public Set<TDpalogicied> getLogicieds() {
		return logicieds;
	}

	public void setLogicieds(Set<TDpalogicied> logicieds) {
		this.logicieds = logicieds;
	}

}