package com.shrcn.tool.rtu.model;

// Generated 2012-2-9 14:04:24 by Hibernate Tools 3.2.2.GA

/**
 * TDpalogicied generated by hbm2java
 */
public class TDpalogicied implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int id;
	private String name;
	private int objectnumber;
	private int objectoffset;
	private int aiobjnumber;
	private int aiobjoffset;
	private int pqobjnumber;
	private int pqobjoffset;
	private int dmdobjnumber;
	private int dmdobjoffset;
	private String cmnaddrsize;
	private String cotsize;
	private String ioasize;
	private String asduaddress;
	private String timemode;
	private String soebuffsize;
	private String delaytime;
	private String clocksynctimeout;
	private String selecttimeout;
	private String recvtimeout;
	private String backscaninterval;
	private String discaninterval;
	private String aiscaninterval;
	private String ciscaninterval;
	private String actrespclass;
	private String girespclass;
	private String cirespclass;
	private String groupgirespclass;
	private String clockrespclass;
	private String initrespclass;
	private String senddoactterm;
	private String sendaoactterm;
	private String buffercos;
	private String paramaddress;
	private String aiaddress;
	private String type20enable;
	private String sendclockevent;
	private String sendcounterdata;
	private String sendchangedata;
	private String sendmultipnt;
	private String send14groupai;
	private String sendclockai;
	private String prioritytype;
	private String seqnumfjoffset;
	private String seqnumaooffset;
	// DISA
	private String localaddress;
	// 103COM
	private String iedtype;
	// dlt645
	private String comaddress;
	// 104 福建规约
	private String type167enable;
	private String iec103addr;
	private String sgupdinterval;

	private TDpamaster master;

	// 103dpa
	private String iedAddr;
	private String totalTime;
	private String linkAddr;

	private String appName;
	private String initCompletedP;
	private String reconnectedP;   
	private String commandRevP;
	private String changeDiP;
	private String sendSoeP;
	private String sendClockP;
	private String sendGroupCallP;
	private String changeAiP;
	public String getAppName() {
		return appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	public TDpalogicied() {
	}

	public TDpalogicied(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getObjectnumber() {
		return this.objectnumber;
	}

	public void setObjectnumber(int objectnumber) {
		this.objectnumber = objectnumber;
	}

	public int getObjectoffset() {
		return this.objectoffset;
	}

	public void setObjectoffset(int objectoffset) {
		this.objectoffset = objectoffset;
	}

	public int getAiobjnumber() {
		return aiobjnumber;
	}

	public void setAiobjnumber(int aiobjnumber) {
		this.aiobjnumber = aiobjnumber;
	}

	public int getAiobjoffset() {
		return aiobjoffset;
	}

	public void setAiobjoffset(int aiobjoffset) {
		this.aiobjoffset = aiobjoffset;
	}

	public int getPqobjnumber() {
		return pqobjnumber;
	}

	public void setPqobjnumber(int pqobjnumber) {
		this.pqobjnumber = pqobjnumber;
	}

	public int getPqobjoffset() {
		return pqobjoffset;
	}

	public void setPqobjoffset(int pqobjoffset) {
		this.pqobjoffset = pqobjoffset;
	}

	public int getDmdobjnumber() {
		return dmdobjnumber;
	}

	public void setDmdobjnumber(int dmdobjnumber) {
		this.dmdobjnumber = dmdobjnumber;
	}

	public int getDmdobjoffset() {
		return dmdobjoffset;
	}

	public void setDmdobjoffset(int dmdobjoffset) {
		this.dmdobjoffset = dmdobjoffset;
	}

	public String getCmnaddrsize() {
		return cmnaddrsize;
	}

	public void setCmnaddrsize(String cmnaddrsize) {
		this.cmnaddrsize = cmnaddrsize;
	}

	public String getCotsize() {
		return cotsize;
	}

	public void setCotsize(String cotsize) {
		this.cotsize = cotsize;
	}

	public String getIoasize() {
		return ioasize;
	}

	public void setIoasize(String ioasize) {
		this.ioasize = ioasize;
	}

	public String getAsduaddress() {
		return asduaddress;
	}

	public void setAsduaddress(String asduaddress) {
		this.asduaddress = asduaddress;
	}

	public String getTimemode() {
		return timemode;
	}

	public void setTimemode(String timemode) {
		this.timemode = timemode;
	}

	public String getSoebuffsize() {
		return soebuffsize;
	}

	public void setSoebuffsize(String soebuffsize) {
		this.soebuffsize = soebuffsize;
	}

	public String getDelaytime() {
		return delaytime;
	}

	public void setDelaytime(String delaytime) {
		this.delaytime = delaytime;
	}

	public String getClocksynctimeout() {
		return clocksynctimeout;
	}

	public void setClocksynctimeout(String clocksynctimeout) {
		this.clocksynctimeout = clocksynctimeout;
	}

	public String getSelecttimeout() {
		return selecttimeout;
	}

	public void setSelecttimeout(String selecttimeout) {
		this.selecttimeout = selecttimeout;
	}

	public String getRecvtimeout() {
		return recvtimeout;
	}

	public void setRecvtimeout(String recvtimeout) {
		this.recvtimeout = recvtimeout;
	}

	public String getBackscaninterval() {
		return backscaninterval;
	}

	public void setBackscaninterval(String backscaninterval) {
		this.backscaninterval = backscaninterval;
	}

	public String getDiscaninterval() {
		return discaninterval;
	}

	public void setDiscaninterval(String discaninterval) {
		this.discaninterval = discaninterval;
	}

	public String getAiscaninterval() {
		return aiscaninterval;
	}

	public void setAiscaninterval(String aiscaninterval) {
		this.aiscaninterval = aiscaninterval;
	}

	public String getCiscaninterval() {
		return ciscaninterval;
	}

	public void setCiscaninterval(String ciscaninterval) {
		this.ciscaninterval = ciscaninterval;
	}

	public String getActrespclass() {
		return actrespclass;
	}

	public void setActrespclass(String actrespclass) {
		this.actrespclass = actrespclass;
	}

	public String getGirespclass() {
		return girespclass;
	}

	public void setGirespclass(String girespclass) {
		this.girespclass = girespclass;
	}

	public String getCirespclass() {
		return cirespclass;
	}

	public void setCirespclass(String cirespclass) {
		this.cirespclass = cirespclass;
	}

	public String getGroupgirespclass() {
		return groupgirespclass;
	}

	public void setGroupgirespclass(String groupgirespclass) {
		this.groupgirespclass = groupgirespclass;
	}

	public String getClockrespclass() {
		return clockrespclass;
	}

	public void setClockrespclass(String clockrespclass) {
		this.clockrespclass = clockrespclass;
	}

	public String getInitrespclass() {
		return initrespclass;
	}

	public void setInitrespclass(String initrespclass) {
		this.initrespclass = initrespclass;
	}

	public String getSenddoactterm() {
		return senddoactterm;
	}

	public void setSenddoactterm(String senddoactterm) {
		this.senddoactterm = senddoactterm;
	}

	public String getSendaoactterm() {
		return sendaoactterm;
	}

	public void setSendaoactterm(String sendaoactterm) {
		this.sendaoactterm = sendaoactterm;
	}

	public String getBuffercos() {
		return buffercos;
	}

	public void setBuffercos(String buffercos) {
		this.buffercos = buffercos;
	}

	public String getParamaddress() {
		return paramaddress;
	}

	public void setParamaddress(String paramaddress) {
		this.paramaddress = paramaddress;
	}

	public String getAiaddress() {
		return aiaddress;
	}

	public void setAiaddress(String aiaddress) {
		this.aiaddress = aiaddress;
	}

	public String getType20enable() {
		return type20enable;
	}

	public void setType20enable(String type20enable) {
		this.type20enable = type20enable;
	}

	public String getSendclockevent() {
		return sendclockevent;
	}

	public void setSendclockevent(String sendclockevent) {
		this.sendclockevent = sendclockevent;
	}

	public String getSendcounterdata() {
		return sendcounterdata;
	}

	public void setSendcounterdata(String sendcounterdata) {
		this.sendcounterdata = sendcounterdata;
	}

	public String getSendchangedata() {
		return sendchangedata;
	}

	public void setSendchangedata(String sendchangedata) {
		this.sendchangedata = sendchangedata;
	}

	public String getSendmultipnt() {
		return sendmultipnt;
	}

	public void setSendmultipnt(String sendmultipnt) {
		this.sendmultipnt = sendmultipnt;
	}

	public String getSend14groupai() {
		return send14groupai;
	}

	public void setSend14groupai(String send14groupai) {
		this.send14groupai = send14groupai;
	}

	public String getSendclockai() {
		return sendclockai;
	}

	public void setSendclockai(String sendclockai) {
		this.sendclockai = sendclockai;
	}

	public String getPrioritytype() {
		return prioritytype;
	}

	public void setPrioritytype(String prioritytype) {
		this.prioritytype = prioritytype;
	}

	public String getSeqnumfjoffset() {
		return seqnumfjoffset;
	}

	public void setSeqnumfjoffset(String seqnumfjoffset) {
		this.seqnumfjoffset = seqnumfjoffset;
	}

	public String getSeqnumaooffset() {
		return seqnumaooffset;
	}

	public void setSeqnumaooffset(String seqnumaooffset) {
		this.seqnumaooffset = seqnumaooffset;
	}

	public String getLocaladdress() {
		return localaddress;
	}

	public void setLocaladdress(String localaddress) {
		this.localaddress = localaddress;
	}

	public String getIedtype() {
		return iedtype;
	}

	public void setIedtype(String iedtype) {
		this.iedtype = iedtype;
	}

	public String getComaddress() {
		return comaddress;
	}

	public void setComaddress(String comaddress) {
		this.comaddress = comaddress;
	}

	public TDpamaster getMaster() {
		return master;
	}

	public void setMaster(TDpamaster master) {
		this.master = master;
	}

	public String getType167enable() {
		return type167enable;
	}

	public void setType167enable(String type167enable) {
		this.type167enable = type167enable;
	}

	public String getIec103addr() {
		return iec103addr;
	}

	public void setIec103addr(String iec103addr) {
		this.iec103addr = iec103addr;
	}

	public String getSgupdinterval() {
		return sgupdinterval;
	}

	public void setSgupdinterval(String sgupdinterval) {
		this.sgupdinterval = sgupdinterval;
	}

	public String getIedAddr() {
		return iedAddr;
	}

	public void setIedAddr(String iedAddr) {
		this.iedAddr = iedAddr;
	}

	public String getTotalTime() {
		return totalTime;
	}

	public void setTotalTime(String totalTime) {
		this.totalTime = totalTime;
	}

	public String getLinkAddr() {
		return linkAddr;
	}

	public void setLinkAddr(String linkAddr) {
		this.linkAddr = linkAddr;
	}

	public String getInitCompletedP() {
		return initCompletedP;
	}

	public void setInitCompletedP(String initCompletedP) {
		this.initCompletedP = initCompletedP;
	}

	public String getReconnectedP() {
		return reconnectedP;
	}

	public void setReconnectedP(String reconnectedP) {
		this.reconnectedP = reconnectedP;
	}

	public String getCommandRevP() {
		return commandRevP;
	}

	public void setCommandRevP(String commandRevP) {
		this.commandRevP = commandRevP;
	}

	public String getChangeDiP() {
		return changeDiP;
	}

	public void setChangeDiP(String changeDiP) {
		this.changeDiP = changeDiP;
	}

	public String getSendSoeP() {
		return sendSoeP;
	}

	public void setSendSoeP(String sendSoeP) {
		this.sendSoeP = sendSoeP;
	}

	public String getSendClockP() {
		return sendClockP;
	}

	public void setSendClockP(String sendClockP) {
		this.sendClockP = sendClockP;
	}

	public String getSendGroupCallP() {
		return sendGroupCallP;
	}

	public void setSendGroupCallP(String sendGroupCallP) {
		this.sendGroupCallP = sendGroupCallP;
	}

	public String getChangeAiP() {
		return changeAiP;
	}

	public void setChangeAiP(String changeAiP) {
		this.changeAiP = changeAiP;
	}

}