package com.shrcn.tool.rtu.model;

import com.shrcn.found.common.util.ObjectUtil;

// Generated 2012-2-9 14:04:24 by Hibernate Tools 3.2.2.GA

/**
 * TDpaobject generated by hbm2java
 */
public class TDpaobject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int id;
	private int pointnumber;
	private int pointoffset;
	private String pointtype;
	private String infotype;
	private String infoaddress;
	private String statuschange;
	private String groupno;
	private String reportclass;
	private String periodmode;
	private String periodtime;
	// dlt645
	private String di2;

	private TDpalogicied logicied;
	// 103dpa
	private String description;
	private String istotalcall;
	private int groupID;

	private String istotal="false";
	public TDpaobject() {
	}

	public TDpaobject(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getPointnumber() {
		return this.pointnumber;
	}

	public void setPointnumber(int pointnumber) {
		this.pointnumber = pointnumber;
	}

	public int getPointoffset() {
		return this.pointoffset;
	}

	public void setPointoffset(int pointoffset) {
		this.pointoffset = pointoffset;
	}

	public String getPointtype() {
		return this.pointtype;
	}

	public void setPointtype(String pointtype) {
		this.pointtype = pointtype;
	}

	public String getInfotype() {
		return this.infotype;
	}

	public void setInfotype(String infotype) {
		this.infotype = infotype;
	}

	public String getInfoaddress() {
		return this.infoaddress;
	}

	public void setInfoaddress(String infoaddress) {
		this.infoaddress = infoaddress;
	}

	public String getStatuschange() {
		return this.statuschange;
	}

	public void setStatuschange(String statuschange) {
		this.statuschange = statuschange;
	}

	public String getGroupno() {
		return this.groupno;
	}

	public void setGroupno(String groupno) {
		this.groupno = groupno;
	}

	public String getReportclass() {
		return this.reportclass;
	}

	public void setReportclass(String reportclass) {
		this.reportclass = reportclass;
	}

	public String getPeriodmode() {
		return this.periodmode;
	}

	public void setPeriodmode(String periodmode) {
		this.periodmode = periodmode;
	}

	public String getPeriodtime() {
		return this.periodtime;
	}

	public void setPeriodtime(String periodtime) {
		this.periodtime = periodtime;
	}

	public String getDi2() {
		return di2;
	}

	public void setDi2(String di2) {
		this.di2 = di2;
	}

	public TDpalogicied getLogicied() {
		return logicied;
	}

	public void setLogicied(TDpalogicied logicied) {
		this.logicied = logicied;
	}

	public int getGroupID() {
		return groupID;
	}

	public void setGroupID(int groupID) {
		this.groupID = groupID;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getIstotalcall() {
		return istotalcall;
	}

	public void setIstotalcall(String istotalcall) {
		this.istotalcall = istotalcall;
	}

	public String getIstotal() {
		return istotal;
	}

	public void setIstotal(String istotal) {
		this.istotal = istotal;
	}
	
	public TDpaobject copy() {
		return (TDpaobject) ObjectUtil.duplicate(this);
	}
}