package com.shrcn.tool.rtu.model;

import java.util.HashSet;
import java.util.Set;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TDpamaster generated by hbm2java
 */
public class TMasterAppPropertyValue implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int id;

	private TMasterApp masterApp;
	private TProperty property;
	private String value;
	public TMasterAppPropertyValue() {
	}
	
	public TMasterAppPropertyValue(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public TMasterApp getMasterApp() {
		return masterApp;
	}

	public void setMasterApp(TMasterApp masterApp) {
		this.masterApp = masterApp;
	}

	public TProperty getProperty() {
		return property;
	}

	public void setProperty(TProperty property) {
		this.property = property;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}