package com.shrcn.tool.rtu.model;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TMasterip generated by hbm2java
 */
public class TMasterip implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int id;
	private String ipaddress;
	private String netgate;
	private int tcpport;
	private int statusPoint;
	private String channalName;

	private TNetchannel net;
	
	public TMasterip() {
	}
	
	public TMasterip(String ipaddress) {
		super();
		this.ipaddress = ipaddress;
	}

	public TMasterip(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	public TNetchannel getNet() {
		return net;
	}

	public void setNet(TNetchannel net) {
		this.net = net;
	}

	public int getStatusPoint() {
		return statusPoint;
	}

	public void setStatusPoint(int statusPoint) {
		this.statusPoint = statusPoint;
	}

	public String getNetgate() {
		return netgate;
	}

	public void setNetgate(String netgate) {
		this.netgate = netgate;
	}

	public int getTcpport() {
		return tcpport;
	}

	public void setTcpport(int tcpPort) {
		this.tcpport = tcpPort;
	}

	public String getChannalName() {
		return channalName;
	}

	public void setChannalName(String channalName) {
		this.channalName = channalName;
	}
	
	
}
