package com.shrcn.tool.rtu.model;

import java.util.HashSet;
import java.util.Set;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TDpamaster generated by hbm2java
 */
public class TMasterApp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int id;

	private TApplication app;
	private TDpamaster dpaMaster;
	private TDpalogicied dpaIED;
	private String RCDName;
	
	private String iedid;
	private String masterName;
	public TMasterApp() {
	}
	
	public TMasterApp(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	public TApplication getApp() {
		return app;
	}

	public void setApp(TApplication app) {
		this.app = app;
	}

	public TDpamaster getDpaMaster() {
		return dpaMaster;
	}

	public void setDpaMaster(TDpamaster dpaMaster) {
		this.dpaMaster = dpaMaster;
	}

	public TDpalogicied getDpaIED() {
		return dpaIED;
	}

	public void setDpaIED(TDpalogicied dpaIED) {
		this.dpaIED = dpaIED;
	}

	public String getRCDName() {
		return RCDName;
	}

	public void setRCDName(String rCDName) {
		RCDName = rCDName;
	}

	public String getIedid() {
		return iedid;
	}

	public void setIedid(String iedid) {
		this.iedid = iedid;
	}

	public String getMasterName() {
		return masterName;
	}

	public void setMasterName(String masterName) {
		this.masterName = masterName;
	}
}