package com.shrcn.tool.rtu.model;

import java.util.HashSet;
import java.util.Set;

/**
 * TApplication generated by hbm2java
 */
public class TNetworkcards  implements java.io.Serializable {

	/**
	 *  
	 */ 
	private static final long serialVersionUID = 1L;
	
     private int id;
     private String name;
     private String ipaddress;
     private String subnet;
 	 private String ethernet;
 	 
 	 
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getIpaddress() {
		return ipaddress;
	}
	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}
	public String getSubnet() {
		return subnet;
	}
	public void setSubnet(String subnet) {
		this.subnet = subnet;
	}
	public String getEthernet() {
		return ethernet;
	}
	public void setEthernet(String ethernet) {
		this.ethernet = ethernet;
	}

 	 
 	 
}


