package com.shrcn.tool.rtu.model;

import java.util.HashSet;
import java.util.Set;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TNetchannel generated by hbm2java
 */
public class TNetchannel extends BaseDpaChannel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int ipnumber;
	private int ipoffset;
	private String allowmultiip;
	private String netmask;//2
	private String maxconnection;//3
	private String confirmtime;//4
	private String stime;//5
	private String idletime;//6
	private String holdtime;//7
	private String stopclearcounter;//8
	private String k_value;	//9
	private String w_value;
	private String clearcos;//10
	private String clearsoe;//11
	private String servicelist;//12
	private String infotype13;//13
	// 新增属性
	private int netType;
	private String localAddr;
	private String procType;
	private String localIP;
	private String tcpSC;
	private String udpSC;
	private String tcpPort;
	private String udpRemotePort;
	private String udpLocalPort;
	private String tmTran;
	private String tmRecv;
	private String bufferSize;
	private String respTimeout;
	private String heartbeat;
	private String netIndex;
	
	//new property
	private String SMasterMIp;//1

	private Set<TMasterip> ips = new HashSet<TMasterip>();

	public TNetchannel() {
	}

	
	
	public TNetchannel(int ipnumber, int ipoffset, int iedoffset, int iednumber,
			String sMasterMIp, String netmask, String maxconnection, String confirmtime, 
			String stime, String idletime, String holdtime, String stopclearcounter,
			String k_value, String clearcos, String clearsoe, String servicelist, String infotype13) {
		super();
		this.ipoffset = ipoffset;
		this.ipnumber = ipnumber;
		super.iednumber = iednumber;
		super.iedoffset = iedoffset;
		this.SMasterMIp = sMasterMIp;
		this.netmask = netmask;
		this.maxconnection = maxconnection;
		this.confirmtime = confirmtime;
		this.stime = stime;
		this.idletime = idletime;
		this.holdtime = holdtime;
		this.stopclearcounter = stopclearcounter;
		this.k_value = k_value;
		this.clearcos = clearcos;
		this.clearsoe = clearsoe;
		this.servicelist = servicelist;
		this.infotype13 = infotype13;
	}



	public TNetchannel(int id) {
		super(id);
	}

	public int getIpnumber() {
		return this.ipnumber;
	}

	public void setIpnumber(int ipnumber) {
		this.ipnumber = ipnumber;
	}

	public int getIpoffset() {
		return this.ipoffset;
	}

	public void setIpoffset(int ipoffset) {
		this.ipoffset = ipoffset;
	}

	public String getAllowmultiip() {
		return this.allowmultiip;
	}

	public void setAllowmultiip(String allowmultiip) {
		this.allowmultiip = allowmultiip;
	}

	public String getNetmask() {
		return this.netmask;
	}

	public void setNetmask(String netmask) {
		this.netmask = netmask;
	}

	public String getMaxconnection() {
		return maxconnection;
	}

	public void setMaxconnection(String maxconnection) {
		this.maxconnection = maxconnection;
	}

	public String getConfirmtime() {
		return confirmtime;
	}

	public void setConfirmtime(String confirmtime) {
		this.confirmtime = confirmtime;
	}

	public String getStime() {
		return stime;
	}

	public void setStime(String stime) {
		this.stime = stime;
	}

	public String getIdletime() {
		return idletime;
	}

	public void setIdletime(String idletime) {
		this.idletime = idletime;
	}

	public String getHoldtime() {
		return holdtime;
	}

	public void setHoldtime(String holdtime) {
		this.holdtime = holdtime;
	}

	public String getStopclearcounter() {
		return stopclearcounter;
	}

	public void setStopclearcounter(String stopclearcounter) {
		this.stopclearcounter = stopclearcounter;
	}

	public String getK_value() {
		return k_value;
	}

	public void setK_value(String k_value) {
		this.k_value = k_value;
	}

	public String getClearcos() {
		return clearcos;
	}

	public void setClearcos(String clearcos) {
		this.clearcos = clearcos;
	}

	public String getClearsoe() {
		return clearsoe;
	}

	public void setClearsoe(String clearsoe) {
		this.clearsoe = clearsoe;
	}

	public String getServicelist() {
		return servicelist;
	}

	public void setServicelist(String servicelist) {
		this.servicelist = servicelist;
	}

	public String getInfotype13() {
		return infotype13;
	}

	public void setInfotype13(String infotype13) {
		this.infotype13 = infotype13;
	}

	public Set<TMasterip> getIps() {
		return ips;
	}

	public void setIps(Set<TMasterip> ips) {
		this.ips = ips;
	}
	
	public void addIp(TMasterip ip){
		ips.add(ip);
	}

	public int getNetType() {
		return netType;
	}

	public void setNetType(int netType) {
		this.netType = netType;
	}

	public String getLocalAddr() {
		return localAddr;
	}

	public void setLocalAddr(String localAddr) {
		this.localAddr = localAddr;
	}

	public String getProcType() {
		return procType;
	}

	public void setProcType(String procType) {
		this.procType = procType;
	}

	public String getLocalIP() {
		return localIP;
	}

	public void setLocalIP(String localIP) {
		this.localIP = localIP;
	}

	public String getTcpSC() {
		return tcpSC;
	}

	public void setTcpSC(String tcpSC) {
		this.tcpSC = tcpSC;
	}

	public String getUdpSC() {
		return udpSC;
	}

	public void setUdpSC(String udpSC) {
		this.udpSC = udpSC;
	}

	public String getTcpPort() {
		return tcpPort;
	}

	public void setTcpPort(String tcpPort) {
		this.tcpPort = tcpPort;
	}

	public String getUdpRemotePort() {
		return udpRemotePort;
	}

	public void setUdpRemotePort(String udpRemotePort) {
		this.udpRemotePort = udpRemotePort;
	}

	public String getUdpLocalPort() {
		return udpLocalPort;
	}

	public void setUdpLocalPort(String udpLocalPort) {
		this.udpLocalPort = udpLocalPort;
	}

	public String getTmTran() {
		return tmTran;
	}

	public void setTmTran(String tmTran) {
		this.tmTran = tmTran;
	}

	public String getTmRecv() {
		return tmRecv;
	}

	public void setTmRecv(String tmRecv) {
		this.tmRecv = tmRecv;
	}

	public String getBufferSize() {
		return bufferSize;
	}

	public void setBufferSize(String bufferSize) {
		this.bufferSize = bufferSize;
	}

	public String getRespTimeout() {
		return respTimeout;
	}

	public void setRespTimeout(String respTimeout) {
		this.respTimeout = respTimeout;
	}

	public String getHeartbeat() {
		return heartbeat;
	}

	public void setHeartbeat(String heartbeat) {
		this.heartbeat = heartbeat;
	}

	public String getW_value() {
		return w_value;
	}

	public void setW_value(String w_value) {
		this.w_value = w_value;
	}

	public String getNetIndex() {
		return netIndex;
	}

	public void setNetIndex(String netIndex) {
		this.netIndex = netIndex;
	}

	public String getSMasterMIp() {
		return SMasterMIp;
	}

	public void setSMasterMIp(String sMasterMIp) {
		this.SMasterMIp = sMasterMIp;
	}
}