package com.shrcn.tool.rtu.model;

import java.util.HashSet;
import java.util.Set;

/**
 * TProperty generated by hbm2java
 */
public class TProperty implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int id;
	private String name;
	private String title;
	private String note;
	private String defaultvalue;
	private int seq;
	private TApptype apptype;
	private Set<TPropertyvalue> apps = new HashSet<TPropertyvalue>();

	public TProperty() {
	}

	public TProperty(int id) {
		this.id = id;
	}

	public TProperty(int id, String name, String title, String note,
			String defaultvalue, int seq) {
		this.id = id;
		this.name = name;
		this.title = title;
		this.note = note;
		this.defaultvalue = defaultvalue;
		this.seq = seq;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getDefaultvalue() {
		return this.defaultvalue;
	}

	public void setDefaultvalue(String defaultvalue) {
		this.defaultvalue = defaultvalue;
	}

	public int getSeq() {
		return this.seq;
	}

	public void setSeq(int seq) {
		this.seq = seq;
	}

	public TApptype getApptype() {
		return apptype;
	}

	public void setApptype(TApptype apptype) {
		this.apptype = apptype;
	}

	public Set<TPropertyvalue> getApps() {
		return apps;
	}

	public void setApps(Set<TPropertyvalue> apps) {
		this.apps = apps;
	}

}
