package com.shrcn.tool.rtu.model;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TPropertyvalue generated by hbm2java
 */
public class TPropertyvalue implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int id;
	private TApplication application;
	private TProperty property;
	private String value;

	public TPropertyvalue() {
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public TApplication getApplication() {
		return application;
	}

	public void setApplication(TApplication application) {
		this.application = application;
	}

	public TProperty getProperty() {
		return property;
	}

	public void setProperty(TProperty property) {
		this.property = property;
	}

}
