package com.shrcn.tool.rtu.model;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TResetmap generated by hbm2java
 */
public class TResetmap extends BaseCalcExpr {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private TDcaSt yxpoint;
	private TDcaSt sendpoint;
	private int yxsaddr;
	private int sendsaddr;

	public TResetmap() {
	}

	public TResetmap(int id) {
		super(id);
	}

	public TResetmap(int id, String expression, int currentnumber,
			int totalnumber, TDcaMx mx, TDcaSt st, TDcaCo co, int saddr) {
		super(id, expression, currentnumber, totalnumber, mx, st, co, saddr);
	}

	public TDcaSt getYxpoint() {
		return yxpoint;
	}

	public void setYxpoint(TDcaSt yxpoint) {
		this.yxpoint = yxpoint;
	}

	public TDcaSt getSendpoint() {
		return sendpoint;
	}

	public void setSendpoint(TDcaSt sendpoint) {
		this.sendpoint = sendpoint;
	}

	public int getYxsaddr() {
		return yxsaddr;
	}

	public void setYxsaddr(int yxsaddr) {
		this.yxsaddr = yxsaddr;
	}

	public int getSendsaddr() {
		return sendsaddr;
	}

	public void setSendsaddr(int sendsaddr) {
		this.sendsaddr = sendsaddr;
	}

	@Override
	public BaseCalcExpr copy() {
		TResetmap expr = new TResetmap();
		assignValues(expr);
		expr.setYxpoint(yxpoint);
		expr.setSendpoint(sendpoint);
		expr.setYxsaddr(yxsaddr);
		expr.setSendsaddr(sendsaddr);
		return expr;
	}

}
