package com.shrcn.tool.rtu.model;

// Generated 2012-2-8 13:44:26 by Hibernate Tools 3.2.2.GA

/**
 * TDipoint generated by hbm2java
 */
public class TSgpoint extends BaseDpaPoint {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String datalength;
	private String aetype;
	private String ontime;
	private String offtime;
	private String counttimes;

	public TSgpoint() {
	}

	public TSgpoint(int id) {
		super(id);
	}

	public String getDatalength() {
		return datalength;
	}

	public void setDatalength(String datalength) {
		this.datalength = datalength;
	}

	public String getAetype() {
		return aetype;
	}

	public void setAetype(String aetype) {
		this.aetype = aetype;
	}

	public String getOntime() {
		return ontime;
	}

	public void setOntime(String ontime) {
		this.ontime = ontime;
	}

	public String getOfftime() {
		return offtime;
	}

	public void setOfftime(String offtime) {
		this.offtime = offtime;
	}

	public String getCounttimes() {
		return counttimes;
	}

	public void setCounttimes(String counttimes) {
		this.counttimes = counttimes;
	}

	@Override
	public void setInfoType(int infoType) {
		// TODO Auto-generated method stub

	}

	@Override
	public void setPointNum(int pointNum) {
		// TODO Auto-generated method stub

	}

}